pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - "#approved-reviews-by>=1"
    actions:
      merge:
        method: merge

- name: Deploy to App Engine
  uses: google-github-actions/deploy-appengine@v0.4.0
